###Register User

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Ben103",
  "email": "Ben103@gmail.com",
  "password": "Ben272008.com"
}

###Login User

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "Ben103",
  "password": "Ben272008.com"
}
### getcurrent user

GET  http://localhost:5000/api/user/me
Content-Type: application/json

{
  "username": "Ben103"
}
###logging in again
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "Ben103",
  "password": "Ben272008.com"
}

### getcurrent user

GET  http://localhost:5000/api/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNzU1NTAzMmY0YTlhYzYzMzgzNmEwYyIsInVzZXJuYW1lIjoiQmVuMTAzIiwiZW1haWwiOiJiZW4xMDNAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODYxMDEzMzAsImV4cCI6MTc4NjcwNjEzMH0.bWy5SgDrSnI2yqH9mbN92halfrv0efy0Wk4EkNUUg90

{
  "username": "Ben103"
}

### testing update user api
PATCH  http://localhost:5000/api/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNzU1NTAzMmY0YTlhYzYzMzgzNmEwYyIsInVzZXJuYW1lIjoiQmVuMTAzIiwiZW1haWwiOiJiZW4xMDNAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODYxMDEzMzAsImV4cCI6MTc4NjcwNjEzMH0.bWy5SgDrSnI2yqH9mbN92halfrv0efy0Wk4EkNUUg90

{
  "username": "Benz103"
}



### testing update user api
PATCH  http://localhost:5000/api/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjZhNzU1NTAzMmY0YTlhYzYzMzgzNmEwYyIsInVzZXJuYW1lIjoiQmVuMTAzIiwiZW1haWwiOiJiZW4xMDNAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3ODYxMDEzMzAsImV4cCI6MTc4NjcwNjEzMH0.bWy5SgDrSnI2yqH9mbN92halfrv0efy0Wk4EkNUUg90

{
  "username": "Benz103"
}
